### ISSUE TITLE
Google Forms link invalid

### ISSUE THREAD

**Issue by armchair-traveller** [Offer1-SanDiego/offer1-interview-exercise#2]
Upon visiting the submission link in the README:

> The form Offer1 Interview Exercise is no longer accepting responses.
> Try contacting the owner of the form if you think this is a mistake.

I'm not trying to submit yet but I hope this is a genuine mistake and we're not being bamboozled. There is no easy way to contact you.

[Link for reference](https://forms.gle/We7VGi73apbECGKL6)

**Comment by tonyhernandez** [comment]
The link has been re-enabled.
