### ISSUE TITLE
Mock data images broken

### ISSUE THREAD

**Issue by armchair-traveller** [Offer1-SanDiego/offer1-interview-exercise#3]
2/3 resources respond with 404.

Just going to use placeholder images for now

(though this prob doesn't really matter if you expect us to implement a backend and come up with with our own mocks or even completely deviate from the example given by omitting/renaming fields. But I imagine a quick a way to go is just to have a database accept duplicates of the current mock)... This is a frontend take-home, right?

**Comment by tonyhernandez** [comment]
But I imagine a quick a way to go is just to have a database accept duplicates of the current mock - yes
This is a frontend take-home, right? - yes

And the image links have been fixed.
